- src/main/java/com/zeroway/user/controller/UserController.java
- src/main/java/com/zeroway/user/entity/User.java
- src/main/java/com/zeroway/user/service/UserService.java
> chore: 소셜 로그인 로직 수정

- src/main/java/com/zeroway/challenge/ChallengeController.java
- src/main/java/com/zeroway/challenge/ChallengeRepository.java
- src/main/java/com/zeroway/challenge/ChallengeService.java
- src/main/java/com/zeroway/challenge/dto/GetChallengeListRes.java
- src/main/java/com/zeroway/challenge/dto/GetChallengeRes.java
- src/main/java/com/zeroway/challenge/dto/PatchChallengeCompleteRes.java
- src/main/resources/application.properties
> Chore: 챌린지 수행 API 수정

- src/main/java/com/zeroway/challenge/ChallengeController.java
- src/main/java/com/zeroway/challenge/ChallengeRepository.java
- src/main/java/com/zeroway/challenge/ChallengeService.java
- src/main/java/com/zeroway/user/controller/UserController.java
- src/main/java/com/zeroway/user/entity/User.java
- src/main/java/com/zeroway/user/service/UserService.java
- src/main/resources/application.properties
Chore: 챌린지 목록 조회 API return값 수정
> Chore: 챌린지 목록 조회 API return값 수정

- src/main/java/com/zeroway/challenge/ChallengeController.java
- src/main/java/com/zeroway/challenge/ChallengeRepository.java
- src/main/java/com/zeroway/challenge/ChallengeService.java
- src/main/java/com/zeroway/user/entity/User.java
- src/main/java/com/zeroway/user/service/UserService.java
> Chore: 챌린지 API 수정

- src/main/java/com/zeroway/challenge/entity/Challenge.java
- src/main/java/com/zeroway/challenge/entity/Level.java
- src/main/java/com/zeroway/common/BaseEntity.java
- src/main/java/com/zeroway/community/entity/PostImage.java
- src/main/java/com/zeroway/community/entity/PostLike.java
- src/main/java/com/zeroway/store/entity/Store.java
- src/main/java/com/zeroway/store/entity/StoreReview.java
- src/main/java/com/zeroway/tips/entity/Term.java
- src/main/java/com/zeroway/tips/entity/Tip.java
- src/main/java/com/zeroway/user/entity/ProviderType.java
- src/main/java/com/zeroway/user/entity/User.java
- src/main/java/com/zeroway/user/service/UserService.java
엔티티 수정 사항 확인해주세요!
- User, PostImage, Challenge, Term, Tip 수정
- Level, PostLike, Store, StoreReview 추가
> refactor: 엔티티 수정 및 추가

- src/main/java/com/zeroway/tips/controller/TipController.java
- src/main/java/com/zeroway/tips/dto/TodayTipsRes.java
- src/main/java/com/zeroway/tips/service/TipService.java
> feat: 오늘의 실천 tip 조회 API 추가

- src/main/java/com/zeroway/community/controller/PostController.java
- src/main/java/com/zeroway/community/dto/CommentListRes.java
- src/main/java/com/zeroway/community/dto/PostListRes.java
- src/main/java/com/zeroway/community/dto/PostRes.java
- src/main/java/com/zeroway/community/entity/Bookmark.java
- src/main/java/com/zeroway/community/entity/CommentLike.java
- src/main/java/com/zeroway/community/entity/PostLike.java
- src/main/java/com/zeroway/community/repository/CommentRepository.java
- src/main/java/com/zeroway/community/repository/CommentRepositoryCustom.java
- src/main/java/com/zeroway/community/repository/CommentRepositoryImpl.java
- src/main/java/com/zeroway/community/repository/PostRepositoryCustom.java
- src/main/java/com/zeroway/community/repository/PostRepositoryImpl.java
- src/main/java/com/zeroway/community/service/PostService.java
- src/test/java/com/zeroway/community/repository/PostRepositoryTest.java
> 커뮤니티 글 조회 api 추가

- src/main/java/com/zeroway/user/controller/UserController.java
- src/main/java/com/zeroway/user/repository/UserRepository.java
- src/main/java/com/zeroway/user/service/UserService.java
- src/main/java/com/zeroway/utils/JwtService.java
> Feat: accessToken 재발급 API 추가

- src/main/java/com/zeroway/community/controller/CommentController.java
- src/main/java/com/zeroway/community/controller/PostController.java
- src/main/java/com/zeroway/community/entity/Comment.java
- src/main/java/com/zeroway/community/entity/CommentLike.java
- src/main/java/com/zeroway/community/repository/comment/CommentLikeRepository.java
- src/main/java/com/zeroway/community/repository/post/PostRepositoryImpl.java
- src/main/java/com/zeroway/community/service/CommentService.java
> 커뮤니티 api 추가

- src/main/java/com/zeroway/common/StatusType.java
- src/main/java/com/zeroway/s3/S3Uploader.java
- src/main/java/com/zeroway/user/controller/UserController.java
- src/main/java/com/zeroway/user/dto/PostUserRes.java
- src/main/java/com/zeroway/user/repository/UserRepository.java
- src/main/java/com/zeroway/user/service/UserService.java
- src/test/java/com/zeroway/user/UserServiceIntegrationTest.java
- src/test/java/com/zeroway/user/UserServiceMockTest.java
> Feat: 로그아웃 API 추가, 로그인 시 프로필사진 설정 추가

- src/main/java/com/zeroway/common/BaseResponseStatus.java
- src/main/java/com/zeroway/user/controller/UserController.java
- src/main/java/com/zeroway/user/dto/PostUserAuthLoginReq.java
- src/main/java/com/zeroway/user/dto/PostUserRes.java
- src/main/java/com/zeroway/user/service/UserService.java
- src/test/java/com/zeroway/user/UserServiceIntegrationTest.java
- src/test/java/com/zeroway/user/UserServiceMockTest.java
> User 가입, 로그인 로직 변경

- src/main/java/com/zeroway/common/BaseResponseStatus.java
- src/main/java/com/zeroway/store/controller/StoreController.java
- src/main/java/com/zeroway/store/dto/StoreRes.java
- src/main/java/com/zeroway/store/entity/Store.java
- src/main/java/com/zeroway/store/service/StoreService.java
> feat: 제로웨이스트샵 상세 조회 API 추가

- src/main/java/com/zeroway/store/controller/StoreController.java
- src/main/java/com/zeroway/store/dto/StoreListRes.java
- src/main/java/com/zeroway/store/service/StoreService.java
Chore: 제로웨이스트샵 리스트 API res Id 추가
> Chore: 제로웨이스트샵 리스트 API res Id 추가

- src/main/java/com/zeroway/community/controller/PostController.java
- src/main/java/com/zeroway/community/entity/Bookmark.java
- src/main/java/com/zeroway/community/entity/Comment.java
- src/main/java/com/zeroway/community/entity/CommentLike.java
- src/main/java/com/zeroway/community/entity/Post.java
- src/main/java/com/zeroway/community/entity/PostImage.java
- src/main/java/com/zeroway/community/entity/PostLike.java
- src/main/java/com/zeroway/community/repository/comment/CommentRepository.java
- src/main/java/com/zeroway/community/repository/comment/CommentRepositoryImpl.java
- src/main/java/com/zeroway/community/repository/post/PostImageRepositoryImpl.java
- src/main/java/com/zeroway/community/repository/post/PostRepositoryImpl.java
- src/main/java/com/zeroway/community/service/CommentService.java
- src/main/java/com/zeroway/community/service/PostLikeService.java
- src/main/java/com/zeroway/community/service/PostService.java
- Post, PostLike, PostImage, Comment, CommentLike, Bookmark 엔티티
> refactor: 커뮤니티 관련 엔티티의 연관관계 매핑 제거

- src/main/java/com/zeroway/common/BaseResponseStatus.java
- src/main/java/com/zeroway/cs/controller/AnnounceController.java
- src/main/java/com/zeroway/cs/controller/FaqController.java
- src/main/java/com/zeroway/cs/controller/QnaController.java
- src/main/java/com/zeroway/cs/dto/QnaListRes.java
- src/main/java/com/zeroway/cs/dto/QnaRes.java
- src/main/java/com/zeroway/cs/entity/QnA.java
- src/main/java/com/zeroway/cs/entity/QnAImage.java
- src/main/java/com/zeroway/cs/repository/QnaImageRepository.java
- src/main/java/com/zeroway/cs/repository/QnaRepository.java
- src/main/java/com/zeroway/cs/repository/QnaRepositoy.java
- src/main/java/com/zeroway/cs/service/FaqService.java
- src/main/java/com/zeroway/cs/service/QnaService.java
Feat: 문의 내역 조회 API 추가
Feat: 문의 내역 상세 조회 API 추가
> Feat: 문의 내역, 상세 조회 API 추가

- src/main/java/com/zeroway/cs/controller/QnaController.java
- src/main/java/com/zeroway/cs/dto/QnaReq.java
- src/main/java/com/zeroway/cs/entity/QnA.java
- src/main/java/com/zeroway/cs/entity/QnAImage.java
- src/main/java/com/zeroway/cs/entity/TypeOfQuestion.java
- src/main/java/com/zeroway/cs/repository/QnaImageRepository.java
- src/main/java/com/zeroway/cs/repository/QnaRepository.java
- src/main/java/com/zeroway/cs/service/QnaService.java
Refactor: cs 연관관계 제거
Feat: 문의 내역 작성 API 추가
> Feat: 문의 내역 작성 API 추가

- src/main/java/com/zeroway/community/controller/PostController.java
> chore: 커뮤니티 글 전체 조회 API 수정

- src/main/java/com/zeroway/community/controller/PostController.java
- src/main/java/com/zeroway/community/dto/BookmarkReq.java
- src/main/java/com/zeroway/community/dto/LikeReq.java
- src/main/java/com/zeroway/community/service/PostLikeService.java
- src/main/java/com/zeroway/community/service/PostService.java
> 커뮤니티 API 수정

- src/main/java/com/zeroway/challenge/controller/ChallengeController.java
- src/main/java/com/zeroway/challenge/service/ChallengeService.java
- src/main/java/com/zeroway/common/BaseResponseStatus.java
- src/main/java/com/zeroway/cs/service/AnnounceService.java
- src/main/java/com/zeroway/cs/service/QnaService.java
Chore: cs, challenge 예외처리 및 챌린지 수행 exp 값 수정
> Chore: cs, challenge 예외처리 및 챌린지 수행 exp 값 수정

- src/main/java/com/zeroway/challenge/controller/ChallengeController.java
- src/main/java/com/zeroway/challenge/repository/UserChallengeRepository.java
- src/main/java/com/zeroway/challenge/service/ChallengeService.java
> Feat: 레벨별 챌린지 API 추가

- .gitignore
- src/main/java/com/zeroway/community/controller/CommentController.java
- src/main/java/com/zeroway/community/service/CommentService.java
> chore: 댓글 좋아요 API 수정

- src/main/java/com/zeroway/common/BaseResponseStatus.java
- src/main/java/com/zeroway/cs/controller/QnaController.java
- src/main/java/com/zeroway/cs/dto/QnaRes.java
- src/main/java/com/zeroway/cs/entity/TypeOfQuestion.java
- src/main/java/com/zeroway/cs/service/QnaService.java
> Chore: 문의 내역 관련 수정사항 반영

- src/main/java/com/zeroway/tips/dto/TodayTipsRes.java
- src/main/java/com/zeroway/tips/service/TipService.java
> chore: 오늘의 팁 조회 API 수정

- src/main/java/com/zeroway/store/service/StoreService.java
> fix: 제로웨이스트샵 리스트 조회 수정

- src/main/java/com/zeroway/challenge/controller/ChallengeController.java
- src/main/java/com/zeroway/challenge/entity/RedisChallenge.java
- src/main/java/com/zeroway/challenge/repository/ChallengeRepository.java
- src/main/java/com/zeroway/challenge/repository/RedisChallengeRepository.java
- src/main/java/com/zeroway/challenge/service/ChallengeService.java
> Chore: 오늘의 챌린지 및 수행 API 로직 수정

- src/main/java/com/zeroway/community/controller/PostController.java
> chore: 커뮤니티 글 조회 API 수정

- src/main/java/com/zeroway/challenge/controller/ChallengeController.java
- src/main/java/com/zeroway/common/BaseResponseStatus.java
- src/main/java/com/zeroway/cs/controller/FaqController.java
- src/main/java/com/zeroway/cs/dto/FaqListRes.java
- src/main/java/com/zeroway/cs/dto/FaqRes.java
- src/main/java/com/zeroway/cs/service/FaqService.java
Feat: 자주 묻는 질문 API & Chore: 챌린지 반환 개수 수정
> Feat: 자주 묻는 질문 API & Chore: 챌린지 반환 개수 수정

- src/test/java/com/zeroway/user/UserServiceIntegrationTest.java
> fix: 테스트 오류 해결

- src/main/java/com/zeroway/challenge/entity/Challenge.java
- src/main/java/com/zeroway/user/entity/User.java
- Challenge 엔티티 level_id 필드 제거
> fix: 챌린지 목록 조회 오류 해결

- src/test/java/com/zeroway/user/UserServiceIntegrationTest.java
> fix: 회원 테스트 오류 수정

- src/main/java/com/zeroway/store/repository/StoreRepository.java
- src/main/java/com/zeroway/store/service/StoreService.java
Feat: 제로웨이스트샵 리스트 API 검색 조건 추가
> Feat: 제로웨이스트샵 리스트 API 검색 조건 추가

- src/main/java/com/zeroway/aop/LogAspect.java
- src/main/java/com/zeroway/community/service/PostService.java
- controllerLogging 메서드 Exception 잡아서 badRequest http 응답 리턴
> chore: LogAspect 예외 처리 추가

- src/main/java/com/zeroway/challenge/controller/ChallengeController.java
- src/main/java/com/zeroway/challenge/service/ChallengeService.java
- src/main/java/com/zeroway/cs/controller/AnnounceController.java
- src/main/java/com/zeroway/cs/entity/Announce.java
- src/main/java/com/zeroway/cs/service/AnnounceService.java
- src/main/java/com/zeroway/cs/service/ReportService.java
Refactor: e.printStackTrace() 삭제
> Refactor: e.printStackTrace() 삭제

- src/main/java/com/zeroway/cs/entity/Announce.java
Fix: Announce 어노테이션 추가 및 에러 해결
> Fix: Announce 어노테이션 추가 및 에러 해결

- src/main/java/com/zeroway/challenge/service/ChallengeService.java
> Chore: 오늘의 챌린지 중복 제거

- src/main/java/com/zeroway/aop/LogAspect.java
- src/main/java/com/zeroway/common/BaseException.java
- src/main/java/com/zeroway/user/controller/UserController.java
- BaseException은 RuntimeException을 상속해야함
> refactor: UserController Exception 처리 AOP 적용

- src/main/java/com/zeroway/user/entity/User.java
> refactor: User 테이블 email unique 인덱스 삭제
